name: CI GitHubActions

# QUANDO parte l'azione?
# 1. Quando fai push sul ramo main
# 2. Quando apri una Pull Request verso il main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # server Linux di GitHub (hope so)
    runs-on: ubuntu-latest

    steps:
    # scarica il codice
    - uses: actions/checkout@v4

    # installa Java 21
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # gradle
    - uses: gradle/actions/setup-gradle@v4

    # rende eseguibile lo script
    - run: chmod +x gradlew

    # lancia i test e la compilazione
    - run: ./gradlew build